require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 1500

Style/FormatStringToken:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: false

Style/OpenStructUse:
  Enabled: false
